# Generated by Django 3.2.9 on 2021-12-01 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Acre (AC)', 'Acre'), ('Alagoas (AL)', 'Alagoas'), ('Amapá (AP)', 'Amapa'), ('Amazonas (AM)', 'Amazonas'), ('Bahia (BA)', 'Bahia'), ('Ceará (CE)', 'Ceara'), ('Distrito Federal (DF)', 'Distrito Federal'), ('Espírito Santo (ES)', 'Espirito Santo'), ('Goiás (GO)', 'Goias'), ('Maranhão (MA)', 'Maranhao'), ('Mato Grosso (MT)', 'Mato Grosso'), ('Mato Grosso do Sul (MS)', 'Mato Grosso Do Sul'), ('Minas Gerais (MG)', 'Minas Gerais'), ('Pará (PA)', 'Para'), ('Paraíba (PB)', 'Paraiba'), ('Paraná (PR)', 'Parana'), ('Pernambuco (PE)', 'Pernambuco'), ('Piauí (PI)', 'Piaui'), ('Rio de Janeiro (RJ)', 'Rio De Janeiro'), ('Rio Grande do Norte (RN)', 'Rio Grande Do Norte'), ('Rio Grande do Sul (RS)', 'Rio Grande Do Sul'), ('Rondônia (RO)', 'Rondonia'), ('Roraima (RR)', 'Roraima'), ('Santa Catarina (SC)', 'Santa Catarina'), ('São Paulo (SP)', 'Sao Paulo'), ('Sergipe (SE)', 'Sergipe'), ('Tocantins (TO)', 'Tocantins')], default='Acre (AC)', max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('start_date', models.CharField(max_length=25)),
                ('end_date', models.CharField(max_length=25)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
